name: Build C# Backup Executables

on:
  push: 
    tags:
      - 'v*'  # z. B. v1.0.0

jobs:
  build:
    name: Build for ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # ggf. anpassen

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained binary
        run: |
          dotnet publish -c Release -r ${{ matrix.rid }} \
            --self-contained true \
            -p:PublishReadyToRun=true \
            -p:PublishSingleFile=true \
            -o publish/${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backup-${{ matrix.rid }}
          path: publish/${{ matrix.rid }}
